name: Generate Docs On Tokens

on:
  push:
    paths:
      - "tokens/**"

jobs:
  generate_token_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Node Dependencies
        run: npm install
      - name: Generate Token Docs
        run: npm run generate-token-docs
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update token docs